### ISSUE TITLE
Issue loading the mod

### ISSUE THREAD

**Issue by housey2k** [Taikelenn/TPSMonitor#1]
i got this error:
![Fabric Loader 20_04_2021 10_16_46](https://user-images.githubusercontent.com/67515570/115402142-85c56b80-a1c1-11eb-9f60-026d0ee4880e.png)

Im using minecraft 1.16.5
![mods 20_04_2021 10_17_30](https://user-images.githubusercontent.com/67515570/115402251-a1c90d00-a1c1-11eb-8885-e2c7fdc0b768.png)
My mod folder

**Comment by Taikelenn** [comment]
The mod seems to be outdated. I will release an update with a day or two.

**Comment by Taikelenn** [comment]
@BrennoMaturino1
I have removed the version restriction, the mod should work correctly on both 1.16.4 and 1.16.5 (and possibly other 1.16 versions). Please redownload the mod from https://github.com/Taikelenn/TPSMonitor/releases/download/v1.0/tpsmonitor-fabric-1.0.jar

**Comment by housey2k** [comment]
> @BrennoMaturino1
> I have removed the version restriction, the mod should work correctly on both 1.16.4 and 1.16.5 (and possibly other 1.16 versions). Please redownload the mod from https://github.com/Taikelenn/TPSMonitor/releases/download/v1.0/tpsmonitor-fabric-1.0.jar

ok thanks, before you updated this i downloaded the mod code and updated this (this motivated me to develop my mods)
